services:
  # The core Elasticsearch database
  elasticsearch:
    image: elasticsearch:8.9.0
    container_name: es-knowledge-base
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - knowledge-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Combined web + auto-ingest service (Flask backend)
  web:
    build: .
    container_name: kb-web
    environment:
      - ES_HOST=http://elasticsearch:9200
      - ES_USER=
      - ES_PASSWORD=
      - INDEX_NAME=knowledge_base
      - DOCUMENTS_DIR=/app/documents
      - FLASK_ENV=development
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./documents:/app/documents
    networks:
      - knowledge-net
    restart: unless-stopped
    command: bash startup.sh  # Uses startup script

  # React frontend development server
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kb-frontend
    ports:
      - "5173:5173"  # Vite dev server port
    volumes:
      # Mount source code for hot reloading
      - ./frontend:/app
      # Prevent local node_modules from overriding container's
      - /app/node_modules
    networks:
      - knowledge-net
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://web:5000

volumes:
  es_data:
    driver: local

networks:
  knowledge-net:
    driver: bridge