services:
  # The core Elasticsearch database
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0
    container_name: es-knowledge-base
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - knowledge-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Document ingestion service (runs once)
  ingest:
    build:
      context: .
      dockerfile: Dockerfile.ingest
    container_name: kb-ingest
    environment:
      - ES_HOST=http://elasticsearch:9200
      - ES_USER=
      - ES_PASSWORD=
      - INDEX_NAME=knowledge_base
      - DOCUMENTS_DIR=/app/documents
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./documents:/app/documents
    networks:
      - knowledge-net
    # No restart policy - runs once and exits
    healthcheck:
      test: ["CMD", "test", "-f", "/app/status/ingest_complete"]
      interval: 15s
      timeout: 10s
      retries: 20
      start_period: 30s

  # Flask backend API service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: kb-backend
    environment:
      - ES_HOST=http://elasticsearch:9200
      - ES_USER=
      - ES_PASSWORD=
      - INDEX_NAME=knowledge_base
      - FLASK_ENV=production
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      elasticsearch:
        condition: service_healthy
      ingest:
        condition: service_completed_successfully
    networks:
      - knowledge-net
    restart: unless-stopped

  # React frontend production server
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: kb-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - knowledge-net
    restart: unless-stopped

volumes:
  es_data:
    driver: local

networks:
  knowledge-net:
    driver: bridge