name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main" ]

# Prevent duplicate runs and cancel in-progress runs on new push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint:
    name: Lint Frontend
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci
      
    - name: Run frontend linting
      working-directory: ./frontend
      run: npm run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    timeout-minutes: 20
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Create test environment file
      run: |
        cat > .env.test << EOF
        ES_HOST=http://elasticsearch:9200
        ES_USER=
        ES_PASSWORD=
        INDEX_NAME=knowledge_base_test
        DOCUMENTS_DIR=/app/test_documents
        FLASK_ENV=testing
        PORT=5000
        TESTING=true
        API_BASE_URL=http://localhost:5000
        EOF
        
    - name: Build and start test services
      run: |
        # Build all services first
        docker compose build
        
        # Start services with test configuration (test override takes precedence)
        docker compose -f docker-compose.yml -f docker-compose.test.yml up -d
        
    - name: Wait for Elasticsearch to be ready
      run: |
        echo "Waiting for Elasticsearch to be ready..."
        timeout 180s bash -c 'until curl -sf http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=30s; do 
          echo "Elasticsearch not ready yet, waiting..."; 
          sleep 5; 
        done'
        echo "✓ Elasticsearch is ready"
        
    - name: Wait for ingest service to complete
      run: |
        echo "Waiting for ingest service to complete document indexing..."
        timeout 300s bash -c '
          while true; do
            # Check if ingest container has exited successfully
            if docker compose ps ingest | grep -q "exited (0)"; then
              echo "✓ Ingest service completed successfully"
              break
            fi
            # Check if container is still running
            if ! docker compose ps ingest | grep -q "Up\|running"; then
              echo "✗ Ingest service failed or stopped unexpectedly"
              docker compose logs ingest
              exit 1
            fi
            echo "Ingest service still running, waiting..."
            sleep 5
          done'
        
    - name: Wait for backend API to be ready
      run: |
        echo "Waiting for backend API to be ready..."
        timeout 120s bash -c 'until curl -sf http://localhost:5000/health; do 
          echo "Backend API not ready yet, waiting..."; 
          sleep 3; 
        done'
        echo "✓ Backend API is ready"
        
    - name: Verify test environment setup
      run: |
        echo "=== Test Environment Verification ==="
        echo "Elasticsearch status:"
        curl -s http://localhost:9200/_cluster/health | jq '.'
        
        echo "Backend health check:"
        curl -s http://localhost:5000/health | jq '.'
        
        echo "Test document count:"
        curl -s http://localhost:5000/stats | jq '.'
        
        echo "Active containers:"
        docker compose ps
        
    - name: Install backend test dependencies
      run: |
        echo "Installing backend test dependencies..."
        docker compose exec -T backend pip install -r requirements-dev.txt
        
    - name: Run backend API tests
      run: |
        echo "Running backend API tests..."
        docker compose exec -T backend python -m pytest tests/ -v --tb=short --maxfail=5 --timeout=60
        
    - name: Set up Node.js for frontend tests
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci
        
    - name: Run frontend tests
      working-directory: ./frontend
      run: |
        echo "Running frontend tests..."
        npm run test:run
        
    - name: Collect service logs on failure
      if: failure()
      run: |
        echo "=== Service Status ==="
        docker compose ps
        
        echo "=== Elasticsearch Logs ==="
        docker compose logs elasticsearch
        
        echo "=== Ingest Service Logs ==="
        docker compose logs ingest
        
        echo "=== Backend Service Logs ==="
        docker compose logs backend
        
        echo "=== Docker System Info ==="
        docker system df
        
    - name: Clean up test environment
      if: always()
      run: |
        echo "Cleaning up test environment..."
        docker compose down -v --remove-orphans
        docker system prune -f --volumes

  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/development'
    
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata for backend image
      id: meta-backend
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend
        tags: |
          type=ref,event=branch
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Extract metadata for ingest image
      id: meta-ingest
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-ingest
        tags: |
          type=ref,event=branch
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Extract metadata for frontend image
      id: meta-frontend
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend
        tags: |
          type=ref,event=branch
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.backend
        push: true
        tags: ${{ steps.meta-backend.outputs.tags }}
        labels: ${{ steps.meta-backend.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Build and push ingest image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.ingest
        push: true
        tags: ${{ steps.meta-ingest.outputs.tags }}
        labels: ${{ steps.meta-ingest.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile.prod
        push: true
        tags: ${{ steps.meta-frontend.outputs.tags }}
        labels: ${{ steps.meta-frontend.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Output image digests
      run: |
        echo "Backend image: ${{ steps.meta-backend.outputs.tags }}"
        echo "Ingest image: ${{ steps.meta-ingest.outputs.tags }}"
        echo "Frontend image: ${{ steps.meta-frontend.outputs.tags }}"